In [1]:
import numpy as np
import timeit

In [2]:
num_rows = int(input('Enter number of entries:'))
num_fts = int(input('Enter number of features:'))

Enter number of entries: 5
Enter number of features: 3


In [3]:
print('Number of Entries:', num_rows, '& Number of Features:', num_fts)

Number of Entries: 5 & Number of Features: 3


# Implement OLS

### Generate a matrix and an array filled with random values using the Python package numpy.


In [4]:
np.random.seed(4)
x_input = np.random.rand(num_rows, num_fts)
np.random.seed(3)
y_actual = np.random.rand(num_rows)

In [5]:
print(x_input)

[[0.96702984 0.54723225 0.97268436]
 [0.71481599 0.69772882 0.2160895 ]
 [0.97627445 0.00623026 0.25298236]
 [0.43479153 0.77938292 0.19768507]
 [0.86299324 0.98340068 0.16384224]]


In [6]:
print(y_actual)

[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695]


### Implement the calculation of the OLS estimator using numpy.

In [7]:
def ols_func_v1(x_input, y_actual):
    mat_1 = np.linalg.inv(np.matmul(np.transpose(x_input), x_input))
    mat_2 = np.matmul(mat_1, np.transpose(x_input))
    final_mat = np.matmul(mat_2, y_actual)
    return(final_mat)

In [8]:
def ols_func_v2(x_input, y_actual):
    mat_1 = np.linalg.inv(np.matmul(np.transpose(x_input), x_input))
    mat_2 = np.matmul(np.transpose(x_input), y_actual)
    final_mat = np.matmul(mat_1, mat_2)
    return(final_mat)

# NEED TO CALCULATE TIME COMPLEXITY

### Compare the execution time of the two variants using the package timeit

In [9]:
import timeit
timeit.timeit("ols_func_v1(x_input, y_actual)", number=100, globals=globals())


0.0032909169999992827

In [10]:
import timeit
timeit.timeit("ols_func_v2(x_input, y_actual)", number=100, globals=globals())


0.001433708000000422

In [11]:
# %%timeit
# ols_func_v1(x_input, y_actual)

In [12]:
# %%timeit
# ols_func_v2(x_input, y_actual)

### OLS using sklearn

In [13]:
from sklearn.linear_model import LinearRegression

In [61]:
reg = LinearRegression().fit(x_input, y_actual)
reg_2 = LinearRegression(fit_intercept=False).fit(x_input, y_actual)

In [62]:
print(reg.coef_)
print(reg_2.coef_)

[ 0.55129031  0.67858281 -0.15896116]
[ 0.36325365  0.59514762 -0.13848539]


In [19]:
reg.intercept_

np.float64(-0.19716132782844187)

In [63]:
beta = ols_func_v2(x_input, y_actual)

In [64]:
print(beta)

[ 0.36325365  0.59514762 -0.13848539]


In [52]:
np.random.seed(3)
x_test = np.random.rand(num_fts, 1)

In [53]:
x_test

array([[0.5507979 ],
       [0.70814782],
       [0.29090474]])

In [54]:
beta = beta.reshape(num_fts, 1)

In [55]:
y_pred = np.matmul(np.transpose(x_test), beta)

In [56]:
y_pred

array([[0.58124578]])

In [58]:
reg.predict(np.transpose(x_test))

array([0.5407826])

In [65]:
reg_2.predict(np.transpose(x_test))

array([0.58124578])

In [48]:
x_test.shape

(1, 3)

In [49]:
beta.shape

(3, 1)

# Implement a loss function

In [70]:
y_actual.shape

(5,)

In [71]:
y_actual_2 = np.random.rand(num_rows)

In [72]:
    y_actual_2.shape

(5,)

In [80]:
%%time
err = 0
for i in range(len(y_actual)):
    err += (y_actual[i]-y_actual_2[i])**2
print('mean squared error:', err)

mean squared error: 1.0208451038829947
CPU times: user 118 µs, sys: 14 µs, total: 132 µs
Wall time: 129 µs


In [81]:
%%time
(np.square(y_actual - y_actual_2)).sum(axis=0)

CPU times: user 99 µs, sys: 1 µs, total: 100 µs
Wall time: 107 µs


np.float64(1.0208451038829947)